name:                blagda
version:             0.1.0.0
github:              "isovector/blagda"
license:             AGPL-3
author:              "Amélia Liao"
maintainer:          "sandy@sandymaguire.me"
copyright:           "Amélia Liao, Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Shake frontend for Agda blogging
category:            Blog

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/blagda#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- Agda
- bytestring
- containers
- directory
- mtl
- pandoc
- pandoc-types
- process
- SHA
- shake
- syb
- tagsoup
- text
- unordered-containers
- uri-encode
- time
- mustache

ghc-options:
  - -Wall

library:
  source-dirs: src

executables:
  blagda:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - blagda
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
